export const tokens = {
  md: {
    source: '#6750A4',
    ref: {
      palette: {
        primary: {
          /* primary */
          0: '#000000',
          10: '#21005D',
          20: '#381E72',
          30: '#4F378B',
          40: '#6750A4',
          50: '#7F67BE',
          60: '#9A82DB',
          70: '#B69DF8',
          80: '#D0BCFF',
          90: '#EADDFF',
          95: '#F6EDFF',
          99: '#FFFBFE',
          100: '#FFFFFF',
        },
        secondary: {
          0: '#000000',
          10: '#1D192B',
          20: '#332D41',
          30: '#4A4458',
          40: '#625B71',
          50: '#7A7289',
          60: '#958DA5',
          70: '#B0A7C0',
          80: '#CCC2DC',
          90: '#E8DEF8',
          95: '#F6EDFF',
          99: '#FFFBFE',
          100: '#FFFFFF',
        },
        error: {
          0: '#000000',
          10: '#410E0B',
          20: '#601410',
          30: '#8C1D18',
          40: '#B3261E',
          50: '#DC362E',
          60: '#E46962',
          70: '#EC928E',
          80: '#F2B8B5',
          90: '#F9DEDC',
          95: '#FCEEEE',
          99: '#FFFBF9',
          100: '#FFFFFF',
        },
        neutral: {
          0: '#000000',
          10: '#1C1B1F',
          20: '#313033',
          30: '#484649',
          40: '#605D62',
          50: '#787579',
          60: '#939094',
          70: '#AEAAAE',
          80: '#C9C5CA',
          90: '#E6E1E5',
          95: '#F4EFF4',
          99: '#FFFBFE',
          100: '#FFFFFF',
        },
        'neutral-variant': {
          0: '#000000',
          10: '#1D1A22',
          20: '#322F37',
          30: '#49454F',
          40: '#605D66',
          50: '#79747E',
          60: '#938F99',
          70: '#AEA9B4',
          80: '#CAC4D0',
          90: '#E7E0EC',
          95: '#F5EEFA',
          99: '#FFFBFE',
          100: '#FFFFFF',
        },
      },
    },
    typescale: {
      display: {
        large: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '57px',
          'line-height': '64px',
          'letter-spacing': '-0.25px',
        },
        medium: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '45px',
          'line-height': '52px',
          'letter-spacing': '0px',
        },
        small: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '36px',
          'line-height': '44px',
          'letter-spacing': '0px',
        },
      },
      headline: {
        large: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '32px',
          'line-height': '40px',
          'letter-spacing': '0px',
        },
        medium: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '28px',
          'line-height': '36px',
          'letter-spacing': '0px',
        },
        small: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '24px',
          'line-height': '32px',
          'letter-spacing': '0px',
        },
      },
      body: {
        large: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '16px',
          'line-height': '24px',
          'letter-spacing': '0.50px',
        },
        medium: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '14px',
          'line-height': '20px',
          'letter-spacing': '0.25px',
        },
        small: {
          'font-family-name': 'Roboto',
          'font-family-style': 'Regular',
          'font-weight': '400px',
          'font-size': '12px',
          'line-height': '16px',
          'letter-spacing': '0.40px',
        },
        label: {
          large: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '14px',
            'line-height': '20px',
            'letter-spacing': '0.10px',
          },
          medium: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '12px',
            'line-height': '16px',
            'letter-spacing': '0.50px',
          },
          small: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '11px',
            'line-height': '16px',
            'letter-spacing': '0.50px',
          },
        },
        title: {
          large: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Regular',
            'font-weight': '400px',
            'font-size': '22px',
            'line-height': '28px',
            'letter-spacing': '0px',
          },
          medium: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '16px',
            'line-height': '24px',
            'letter-spacing': '0.15px',
          },
          small: {
            'font-family-name': 'Roboto',
            'font-family-style': 'Medium',
            'font-weight': '500px',
            'font-size': '14px',
            'line-height': '20px',
            'letter-spacing': '0.10px',
          },
        },
      },
    },
  },
};
